/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphane.otomasyonu;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ebubekir
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_giris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_cks = new javax.swing.JButton();
        txt_k_adi = new java.awt.TextField();
        txt_sfr = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 250));

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Kullanıcı Şifresi:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 80, 130, 14);

        btn_giris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/otomasyonu/11.png"))); // NOI18N
        btn_giris.setToolTipText("Giriş İçin Tıklayınız");
        btn_giris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_giris);
        btn_giris.setBounds(200, 160, 100, 100);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Kullanıcı Adı:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 80, 80, 14);

        btn_cks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/otomasyonu/btnb04.gif"))); // NOI18N
        btn_cks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cksActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cks);
        btn_cks.setBounds(460, 250, 120, 40);

        txt_k_adi.setText("ebubekir");
        jPanel1.add(txt_k_adi);
        txt_k_adi.setBounds(160, 110, 81, 20);

        txt_sfr.setText("123");
        jPanel1.add(txt_sfr);
        txt_sfr.setBounds(260, 110, 85, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kutuphane/otomasyonu/windows_7_black_login_background_by_jeaglej-d7a56l5.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 580, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cksActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_cksActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
       String param[]= {txt_k_adi.getText(),txt_sfr.getText() } ;    
         try {
         baglanti bgl= new baglanti();
         bgl.baglanti();
         
     ResultSet dgr;
     CallableStatement calstat = bgl.con.prepareCall("{call kgirisi(?,?)}");
          calstat.setString(new baglanti().k_girisi_par[0], param[0]);
          calstat.setString(new baglanti().k_girisi_par[1], param[1]);
          dgr = calstat.executeQuery();
          while(dgr.next())
          {
             
              if ("1".equals(dgr.getObject(1).toString()))
              {
                  hide();
                  new Anamenu().setVisible(true);
              }
              else
              {
                  JOptionPane.showMessageDialog(null,bgl.k_girisi_hata,bgl.genel_mesaj,2);
              }
          }
         }
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(null, e.getMessage() ,"Hata", 1);
         }
    }//GEN-LAST:event_btn_girisActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cks;
    private javax.swing.JButton btn_giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField txt_k_adi;
    private java.awt.TextField txt_sfr;
    // End of variables declaration//GEN-END:variables
}
